In [9]:
import pandas as pd
import numpy as np

In [10]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = 'API_KEY'
from tmdbv3api import Movie

tmdb_movie = Movie() 
def get_titles(x):
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['original_title']:
          return data_json['original_title']
      else:
          return np.NaN

In [11]:
movies = pd.read_csv('main_data.csv')

handle: main_data.csv
main_data.csv

In [12]:
movies.drop('summary', axis=1, inplace=True)

In [13]:
movies

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,overview
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,"In the 22nd century, a paraplegic Marine is di..."
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,"Captain Barbossa, long believed to be dead, ha..."
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,A cryptic message from Bond’s past sends him o...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Following the death of District Attorney Harve...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens,Thirty years after defeating the Galactic Empi...
...,...,...,...,...,...,...,...
6422,Garth Jennings,Matthew McConaughey,Reese Witherspoon,Scarlett Johansson,Family Comedy Animation Drama Music,sing 2,Buster and his new cast now have their sights ...
6423,Matthew Vaughn,Ralph Fiennes,Gemma Arterton,Rhys Ifans,War Action Thriller Adventure,the king's man,As a collection of history's worst tyrants and...
6424,Joel Coen,Denzel Washington,Frances McDormand,Corey Hawkins,Drama Thriller War,the tragedy of macbeth,"Macbeth, the Thane of Glamis, receives a proph..."
6425,Erwin brothers,Zachary Levi,Anna Paquin,Dennis Quaid,Drama,american underdog,"The true story of Kurt Warner, who went from a..."
6426,Joe Wright,Peter Dinklage,Haley Bennett,Kelvin Harrison Jr.,Drama Comedy History Romance,cyrano,A musical/drama adaptation of the life of Cyra...

In [14]:
movies[movie_title] = movies['movie_title'].map(lambda x: get_title(x))

NameError: name 'get_title' is not defined